//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCustomer()
        {
            this.TblProcess = new HashSet<TblProcess>();
        }

        public int CustomerId { get; set; }
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz!")]
        [StringLength(50,ErrorMessage ="Lüfen 50 karakter uzunluðunda veri giriniz")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        [StringLength(50, ErrorMessage = "Lüfen en fazla 50 karakter uzunluðunda veri giriniz!")]
        public string CustomerSurname { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProcess> TblProcess { get; set; }
    }
}
